[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = 'TSUpdate'

[[plugins]]
repo = 'github/copilot.vim'
rev = 'release'

[[plugins]]
repo = 'CopilotC-Nvim/CopilotChat.nvim'
rev = 'canary'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'

[[plugins]]
repo = 'mikinovation/nvim-gitui'

[[plugins]]
repo = 'jparise/vim-graphql'
