[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'windwp/nvim-ts-autotag'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
do = 'TSUpdate'

[[plugins]]
repo = 'github/copilot.vim'
rev = 'release'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
