[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
