name: lint

on:
  push:
    branches:
      - "*"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install required packages
        run: |
          apt install shellcheck
          pip install --upgrade pip
          pip install vim-vint
