name: ubuntu

on:
  push:
    branch:
      - "*"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run setup ubuntu
        run: ${GITHUB_WORKSPACE}/setup-ubuntu.sh

      - name: Run deploy.sh
        run: ${GITHUB_WORKSPACE}/deploy.sh
